spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:EMOJI
logging:
  level.org.hibernate: DEBUG
  pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS